### ISSUE TITLE
Bletch mame error parsing XML on MAME .249

### ISSUE THREAD

**Issue by jvidalw** [npwoods/bletchmame#393] opened 2022-10-30 22:03 UTC
Hi!
I'm giving Bletchmame a try, but it doesn't work, unfortunantely.
After setting the initial parameters, pointing it to the MAME exe, it starts building the database, but it stops after a moment, showing a dialog with this error:

"Error parsing XML from MAME -listxml: 62679:2: Error parsing attribute "refresh" (text="60,000000")"

What can I do?
I'm using the official MAME .249 x64 exe.

**Comment by npwoods** [comment] 2022-10-30 22:28
I'll take a look; I assume you're not having problems with MAME 0.248?

**Comment by jvidalw** [comment] 2022-10-30 23:25
It's the first time I use Bletchmame, I don't know  if it works with MAME .248 (or not).

**Comment by npwoods** [comment] 2022-10-31 13:34
I can't reproduce this problem, but I suspect I know what this might be.

Can you run `-listxml` and tell me what `refresh` attributes look like?  It should look like this:
```
                <display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="60.000000" pixclock="5156160" htotal="328" hbend="0" hbstart="256" vtotal="262" vbend="0" vbstart="224" />
````
`refresh` attributes should use periods for decimal points without regard to locale.  But MAME has had this problem before.  Is this happening for you?

**Comment by jvidalw** [comment] 2022-10-31 16:56
yes, they look exactly like that.
with periods for decimals 
I even searched for "60,0" and found nothing (I dumped the output to a .txt file)

**Comment by jvidalw** [comment] 2022-10-31 17:20
I just ran BletchMame again and now the error is about a refresh rate being "59,922743", but I searched the file for 59,92 and found nothing.
I searched for 59.922743 and found it right aaway, correctly displayed, with a period not a comma,

**Comment by jvidalw** [comment] 2022-10-31 17:27
update: this is weird, now I switched to the unofficial 32 bit mame and this time it worked.
I renamed the 64 bit exe to MAME64.exe (and that's the one I selected the first time), could this be a problem?? 
Now I chose MAME.exe (the 32 bit version) and it worked.

**Comment by npwoods** [comment] 2022-10-31 20:08
> update: this is weird, now I switched to the unofficial 32 bit mame and this time it worked.
> edit: even weirder, I switched back to MAME64.EXE and it still works, no errors like the first time.

This is incredibly weird, and I'm at a loss to explain either of these.

> Does Bletchmame support zipped snaps (i.e. snap.zip in the snap folder)?? I can't get my snapshots to show in the UI

Yes, but you have to add a path to your `snap.zip` to the Paths dialog

**Comment by jvidalw** [comment] 2022-10-31 22:10
it won't let me, I can only add the path to the folder,not the zip file (OR so I believe, I'll try again, thanks!)

**Comment by npwoods** [comment] 2022-11-01 12:21
I know what is going on here.  Unfortunately, Windows doesn't let you have a file dialog that works for both files and directories.  You have to copy and paste the path to `snap.zip` in the path list.

As you might expect, this has come up before.

**Comment by npwoods** [comment] 2022-11-03 19:45
Closing this out because I cannot reproduce this; if we can get more info, let me know!

**Closed by npwoods** 2022-11-03 19:45 UTC
