### ISSUE TITLE
Mame Dir

### ISSUE THREAD

**Issue by Zxquad** [npwoods/bletchmame#1] opened 2019-11-13 18:31 UTC
Hi, on my side all my roms dir are +- like this D:\Mame\MAME ROMs (bios-devices) on Win10, when I point to them,  Bletchmame don't start the game and give me an error, if I rename the dir to only MAME it's works, is it possible to fix this ?

hope it's the good place to but a remark, I never used GitHub before ....

**Comment by npwoods** [comment] 2019-11-14 14:20
This is the right place.  Congratulations on reporting issue number one :-)

In any case, I couldn't reproduce the problem.  Locally I have my ROMs in D:\MameFiles\roms and I changed it to "D:\MameFiles\MAME Roms", changed the ROMs path in Settings --> Paths, and it worked.

Can you confirm that you set up the ROMs directory properly in Settings --> Paths?

**Comment by Zxquad** [comment] 2019-11-15 17:40
Yes, I tried with all my roms path ..... not working ....

![image](https://user-images.githubusercontent.com/26525323/68961369-87bc1b80-07d2-11ea-8e6c-31f87b32b0d4.png)

with dir without spaces ... not working ...

![image](https://user-images.githubusercontent.com/26525323/68961622-1761ca00-07d3-11ea-8656-0ba8a01faef7.png)
![image](https://user-images.githubusercontent.com/26525323/68961677-33656b80-07d3-11ea-88c6-190ffa34abef.png)

but if I finally remove "(" and ")" it works !!!!!
also if I add the spaces ....

![image](https://user-images.githubusercontent.com/26525323/68963386-1a5eb980-07d7-11ea-83dc-270a6611b861.png)

![image](https://user-images.githubusercontent.com/26525323/68963397-2185c780-07d7-11ea-918b-757b60eba61d.png)

ll be great to fix this if possible .... :)

**Comment by npwoods** [comment] 2019-11-16 19:12
Ok, I managed to find a problem.  For various reasons I was gagging on paths with parentheses in them.  I have fixed that problem (feel free to grab 1.5.0.2), but I'm unwilling to close this bug until I'm confident this addresses all of your problems recognizing paths.

Thanks!

**Comment by Zxquad** [comment] 2019-11-17 19:10
Hi, 
Thx dir working just fine now on my side ;) with on version 1.5.3.

Also tried 1.5.2 but this one didn't start here .....

**Comment by npwoods** [comment] 2019-11-17 21:56
1.5.0.2 was bad; I tried to slim down the executable by using link time optimization, but that did not work out, so I reverted it.

Anyways I'm closing out this issue now that we've confirmed your problem has been fixed.  Keep the reports coming!

**Closed by npwoods** 2019-11-17 21:56 UTC
